# Generated by Django 4.2.7 on 2023-11-27 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0003_sharedpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SharedPost',
        ),
    ]
